# Repository의 Actions 탭에 나타날 Workflow 이름으로 필수 옵션은 아닙니다.
name: deploy

# Workflow를 실행시키기 위한 Event 목록입니다.
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# 해당 Workflow의 하나 이상의 Job 목록입니다.
jobs:
  build:
    runs-on: ubuntu-20.04
    environment: production
    env:
      AWS_REGION: ap-northeast-2
      CODE_DEPLOY_APPLICATION_NAME: 99-clone
      CODE_DEPLOY_DEPLOYMENT_GROUP_NAME: 99-clone
      AWS_S3_BUCKET_NAME: 99-project-mini
      DB_DIALECT: mysql

    steps:
      # 해당 레포지토리로 check-out하는 Action을 불러왔습니다.
      - name: Checkout
        uses: actions/checkout@v2

      # Node 환경을 설정하여 npm 커맨드를 사용할 수 있도록 하는 Action을 불러옵니다.
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: create env file
        working-directory: ./
        run: |
          pwd
          touch .env
          echo PORT=${{ secrets.PORT }} >> .env
          echo AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} >> .env
          echo AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} >> .env
          echo AWS_S3_BUCKET_NAME=${{ env.AWS_S3_BUCKET_NAME }} >> .env
          echo AWS_REGION=${{ env.AWS_REGION }} >> .env
          echo KEY=${{ secrets.KEY }} >> .env
          echo client_id=${{ secrets.CLIENT_ID }} >> .env
          echo DEV_DB_USERNAME=${{ secrets.DB_USERNAME }} >> .env
          echo DEV_DB_PASSWORD=${{ secrets.DB_PASSWORD }} >> .env
          echo DEV_DB_DATABASE=${{ secrets.DB_DATABASE }} >> .env
          echo DEV_DB_HOST=${{ secrets.DB_HOST }} >> .env
          echo DEV_DB_DIALECT=${{ env.DB_DIALECT }} >> .env
          cat .env

      - name: zip file
        run: zip -r deploy.zip ./scripts ./appspec.yml ./.env ./package.json ./db ./src ./app.js

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: upload to S3
        run: aws s3 cp --region ap-northeast-2 ./deploy.zip s3://99-clone/deploy/

      - name: deploy with AWS codeDeploy
        run: aws deploy create-deployment --application-name ${{ env.CODE_DEPLOY_APPLICATION_NAME }} --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name ${{ env.CODE_DEPLOY_DEPLOYMENT_GROUP_NAME }} --s3-location bucket=99-clone,bundleType=zip,key=deploy/deploy.zip
